# Used for quick patch updates to api.bel.bio
# Have to mount the bel python package to /bel

FROM python:3.6
MAINTAINER  William Hayes whayes@openbel.org

EXPOSE 8000

RUN groupadd -g 1000 api && useradd api -u 1000 -g 1000 && mkdir /app && chown -R api:api /app

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
COPY docker/bel /bel
RUN pip install -r /app/requirements.txt
RUN pip install -e /bel

COPY ./api /app

USER api

# HEALTHCHECK CMD curl --fail http://localhost:8000/healthcheck || exit 1

# https://sebest.github.io/post/protips-using-gunicorn-inside-a-docker-image/
CMD gunicorn --config /app/gunicorn.conf --log-config /app/gunicorn_log.conf -b 0.0.0.0:8000 app:api
